# Generated by Django 5.2.1 on 2026-09-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='expense_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('category', models.CharField(choices=[('food', 'Food'), ('groceries', 'Groceries'), ('transportation', 'Transportation'), ('fuel', 'Fuel'), ('rent', 'Rent'), ('utilities', 'Utilities'), ('electricity', 'Electricity'), ('water', 'Water'), ('internet', 'Internet'), ('phone', 'Phone'), ('healthcare', 'Healthcare'), ('medicine', 'Medicine'), ('insurance', 'Insurance'), ('education', 'Education'), ('shopping', 'Shopping'), ('clothing', 'Clothing'), ('entertainment', 'Entertainment'), ('subscriptions', 'Subscriptions'), ('travel', 'Travel'), ('hotel', 'Hotel'), ('personal_care', 'Personal Care'), ('fitness', 'Fitness & Gym'), ('sports', 'Sports'), ('gifts', 'Gifts'), ('donations', 'Donations'), ('family', 'Family'), ('pets', 'Pets'), ('home', 'Home & Furniture'), ('electronics', 'Electronics'), ('maintenance', 'Maintenance'), ('taxes', 'Taxes'), ('fees', 'Fees & Charges'), ('debt_payment', 'Debt Payment'), ('loan', 'Loan'), ('investment', 'Investment'), ('savings', 'Savings'), ('business', 'Business'), ('work', 'Work'), ('books', 'Books'), ('coffee', 'Coffee'), ('restaurants', 'Restaurants'), ('alcohol', 'Alcohol'), ('other', 'Other')])),
                ('description', models.TextField()),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
